# Generated by Django 3.2.6 on 2021-08-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleRegNumber', models.CharField(max_length=50, unique=True)),
                ('vehicleType', models.IntegerField(choices=[(1, 'bike'), (2, 'car')])),
                ('vehicleSpec', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField()),
                ('bookingUpto', models.DateTimeField()),
                ('vehicleOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='bookingApi.userprofile')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ManyToManyField(related_name='vehicle', to='bookingApi.Vehicle')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='bookingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetimeFrom', models.DateTimeField()),
                ('datetimeTo', models.DateTimeField()),
                ('bookingStatus', models.BooleanField()),
                ('booked_datetime', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='bookingApi.userprofile')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
