# Generated by Django 3.2.6 on 2021-08-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingApi', '0003_bookingdate_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicleName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
